### PR TITLE
Add #[global] on instances 

### PR DESCRIPTION
**Pull request by yforster**
As discussed with @MevenBertrand, this is necessary for the generated code to be compatible with Coq 8.17 and higher

### CODE REVIEW

**Comment by MevenBertrand** [comment]
Looks like by changing the instances from global to local, this breaks examples which do not re-export them, annoying…

**Comment by yforster** [comment]
Maybe we stay with export and let users control import of hints via 
import_categories? 
https://coq.inria.fr/refman/language/core/modules.html#grammar-token-import_categories

**Comment by MevenBertrand** [comment]
Sounds like an easy solution, should be good enough for now, and we can do the "proper" change later on.

**Comment by MevenBertrand** [comment]
Yeah, not ideal, but I guess we'll have to live with this for now… It's still an improvement over the current setup, which behaves like `#[global]` in 8.13, but without even being explicit.

**Pull request merged**
